include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y   +=  lg4591.o
obj-y   +=  nt35590_auo50_ykl.o
obj-y   +=  otm1281a_au_dsi.o
obj-y   +=  otm1283_auo_dsi.o


