/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat Oct 11 00:22:34 2014
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


